Repository opencovid19-fr/data, pull requests merged in 2020-04, with the labels that each got.

#483 ADD ARS Mayotte 30/03
  agences-regionales-sante/mayotte/2020-03-30.yaml
Labels: à vérifier

#459 Ars bretagne 2020 03 29.yaml
  agences-regionales-sante/bretagne/2020-03-29.yaml
  agences-regionales-sante/bretagne/2020-03-29_première_version.yaml
Labels: anomalies

#440 ADD ARS Auvergne-Rhône-Alpes 28/03
  agences-regionales-sante/auvergne-rhone-alpes/2020-03-28.yaml
Labels: anomalies

#482 ADD ARS Mayotte 29/03
  agences-regionales-sante/mayotte/2020-03-29.yaml
Labels: anomalies

#477 Données du 31 mars 2020
  ministere-sante/2020-03-31.yaml
Labels: à vérifier

#476 Bulletin ARS Pays de la Loire du 31-03-2020
  agences-regionales-sante/pays-de-la-loire/2020-03-31.yaml
  agences-regionales-sante/pays-de-la-loire/2020-04-01.yaml
Labels: à vérifier

#433 ADD ARS HDF 27/03
  agences-regionales-sante/hauts-de-france/2020-03-27.yaml
Labels: anomalies

#485 ADD ARS Mayotte 02/04
  agences-regionales-sante/mayotte/2020-04-02.yaml
Labels: à vérifier

#486 ADD ARS Mayotte 03/04
  agences-regionales-sante/mayotte/2020-04-03.yaml
Labels: à vérifier

#484 ADD ARS Mayotte 31/03
  agences-regionales-sante/mayotte/2020-03-31.yaml
Labels: à vérifier

#494 ADD Nouvelle-Calédonie 27/03
  agences-regionales-sante/nouvelle-caledonie/2020-03-27.yaml
Labels: à vérifier

#495 ADD Nouvelle-Calédonie 28/03
  agences-regionales-sante/nouvelle-caledonie/2020-03-28.yaml
Labels: à vérifier

#497 ADD Nouvelle-Calédonie 29/03
  agences-regionales-sante/nouvelle-caledonie/2020-03-29.yaml
Labels: à vérifier

#498 ADD Nouvelle-Calédonie 30/03
  agences-regionales-sante/nouvelle-caledonie/2020-03-30.yaml
Labels: à vérifier

#499 ADD Nouvelle-Calédonie 31/03
  agences-regionales-sante/nouvelle-caledonie/2020-03-31.yaml
Labels: à vérifier

#500 ADD Nouvelle-Calédonie 01/04
  agences-regionales-sante/nouvelle-caledonie/2020-04-01.yml
Labels: à vérifier

#512 ADD DSP Polynésie française 27/03
  agences-regionales-sante/polynesie-francaise/2020-03-27.yaml
Labels: à vérifier

#513 ADD DSP Polynésie française 28/03
  agences-regionales-sante/polynesie-francaise/2020-03-28.yaml
Labels: à vérifier

#518 ADD DSP Polynésie française 02/04
  agences-regionales-sante/polynesie-francaise/2020-04-02.yaml
Labels: à vérifier

#524 ADD DSP Polynésie française 08/04
  agences-regionales-sante/polynesie-francaise/2020-04-08.yaml
Labels: à vérifier

#514 ADD DSP Polynésie française 29/03
  agences-regionales-sante/polynesie-francaise/2020-03-29.yaml
Labels: à vérifier

#522 ADD DSP Polynésie française 06/04
  agences-regionales-sante/polynesie-francaise/2020-04-06.yaml
Labels: à vérifier

#521 ADD DSP Polynésie française 05/04
  agences-regionales-sante/polynesie-francaise/2020-04-05.yaml
Labels: à vérifier

#517 ADD DSP Polynésie française 01/04
  agences-regionales-sante/polynesie-francaise/2020-03-31.yaml
Labels: à vérifier

#505 ADD Nouvelle-Calédonie 03/04
  agences-regionales-sante/nouvelle-caledonie/2020-04-03.yml
Labels: à vérifier

#519 ADD DSP Polynésie française 03/04
  agences-regionales-sante/polynesie-francaise/2020-04-03.yaml
Labels: anomalies, à vérifier

#523 ADD DSP Polynésie française 07/04
  agences-regionales-sante/polynesie-francaise/2020-04-07.yaml
Labels: anomalies, à vérifier

#516 ADD DSP Polynésie française 31/03
  agences-regionales-sante/polynesie-francaise/2020-03-31.yaml
Labels: à vérifier

#515 ADD DSP Polynésie française 30/03
  agences-regionales-sante/polynesie-francaise/2020-03-30.yaml
Labels: à vérifier
