Repository opencovid19-fr/data, pull requests merged in 2020-03, with the labels that each got.

#27 hauts-de-france: 26/02, 9,10,14/03
  agences-regionales-sante/hauts-de-france/2020-02-26.yaml
  agences-regionales-sante/hauts-de-france/2020-03-09.yaml
  agences-regionales-sante/hauts-de-france/2020-03-10.yaml
  agences-regionales-sante/hauts-de-france/2020-03-13.yaml
  agences-regionales-sante/hauts-de-france/2020-03-14.yaml
Labels: À vérifier

#25 centre-val-de-loire - add yaml: 05/03, 06/03 and 12/03
  agences-regionales-sante/centre-val-de-loire/2020-03-05.yaml
  agences-regionales-sante/centre-val-de-loire/2020-03-06.yaml
  agences-regionales-sante/centre-val-de-loire/2020-03-08.yaml
  agences-regionales-sante/centre-val-de-loire/2020-03-10.yaml
  agences-regionales-sante/centre-val-de-loire/2020-03-11.yaml
  agences-regionales-sante/centre-val-de-loire/2020-03-12.yaml
  agences-regionales-sante/centre-val-de-loire/2020-03-14.yaml
Labels: À vérifier

#24 ARS Rhône-Alpes + Normandie 2020-03-14
  agences-regionales-sante/auvergne-rhone-alpes/2020-03-14.yaml
  agences-regionales-sante/normandie/2020-03-14.yaml
Labels: à vérifier

#14 Ajout ARS Nouvelle-Aquitaine avec historique
  agences-regionales-sante/nouvelle-aquitaine/2020-01-24.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-02-29.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-03.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-04.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-05.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-06.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-07.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-08.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-09.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-10.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-11.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-12.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-13.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-14.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-15.yaml
  agences-regionales-sante/nouvelle-aquitaine/README.md
Labels: à vérifier

#37 Ile-de-France: add 13,14/03
  agences-regionales-sante/ile-de-france/2020-03-06.yaml
  agences-regionales-sante/ile-de-france/2020-03-13.yaml
  agences-regionales-sante/ile-de-france/2020-03-14.yaml
Labels: en attente

#67 auvergne-rhone-alpes: add 2020-03-15
  agences-regionales-sante/auvergne-rhone-alpes/2020-03-15.yaml
Labels: à vérifier

#90 Ajout ARS Nouvelle Aquitaine 2020-02-17
  agences-regionales-sante/nouvelle-aquitaine/2020-03-17.yaml
Labels: en attente, good first issue

#87 Ajout ARS Guadeloupe COM 03/03 à 15/03
  agences-regionales-sante/saint-barthelemy/2020-03-06.yaml
  agences-regionales-sante/saint-barthelemy/2020-03-09.yaml
  agences-regionales-sante/saint-barthelemy/2020-03-13.yaml
  agences-regionales-sante/saint-barthelemy/2020-03-14.yaml
  agences-regionales-sante/saint-barthelemy/2020-03-15.yaml
  agences-regionales-sante/saint-martin/2020-03-06.yaml
  agences-regionales-sante/saint-martin/2020-03-09.yaml
  agences-regionales-sante/saint-martin/2020-03-13.yaml
  agences-regionales-sante/saint-martin/2020-03-14.yaml
  agences-regionales-sante/saint-martin/2020-03-15.yaml
Labels: en attente

#110 ARS 17 et 18 mars
  agences-regionales-sante/corse/2020-03-18.yaml
  agences-regionales-sante/grand-est/2020-03-17.yaml
  agences-regionales-sante/ile-de-france/2020-03-17.yaml
  agences-regionales-sante/normandie/2020-03-18.yaml
  agences-regionales-sante/pays-de-la-loire/2020-03-17.yaml
Labels: anomalies

#131 ARS PACA 18/03
  agences-regionales-sante/provence-alpes-cote-dazur/2020-03-18.yaml
Labels: anomalies

#117 Ajout ARS Nouvelle Aquitaine 2020-03-18
  agences-regionales-sante/nouvelle-aquitaine/2020-03-18.yaml
Labels: anomalies

#124 ARS Hauts-de-France 18/03
  agences-regionales-sante/hauts-de-france/2020-03-18.yaml
Labels: anomalies

#126 ARS Bourgogne-Franche-Comté 18/03
  agences-regionales-sante/bourgogne-franche-comte/2020-03-18.yaml
Labels: anomalies

#111 Prefecture aisne allier
  prefectures/02/2020-03-02.yaml
  prefectures/02/2020-03-03.yaml
  prefectures/02/2020-03-04.yaml
  prefectures/02/2020-03-05.yaml
  prefectures/02/2020-03-07.yaml
  prefectures/02/2020-03-09.yaml
  prefectures/02/2020-03-10.yaml
  prefectures/02/README.md
  prefectures/03/2020-03-12.yaml
Labels: à vérifier

#139 ajout bulletin 18 mars 2020 pays de la loire
  agences-regionales-sante/pays-de-la-loire/2020-03-18.yaml
Labels: anomalies

#151 ARS Bretagne 19/03
  agences-regionales-sante/bretagne/2020-03-19.yaml
Labels: anomalies

#155 update martinique 2020-03-19
  agences-regionales-sante/martinique/2020-03-19.yaml
Labels: anomalies

#156 Ajout des fichiers pour la Réunion
  agences-regionales-sante/reunion/2020-03-11.yaml
  agences-regionales-sante/reunion/2020-03-12.yaml
  agences-regionales-sante/reunion/2020-03-13.yaml
  agences-regionales-sante/reunion/2020-03-15.yaml
  agences-regionales-sante/reunion/2020-03-17.yaml
  agences-regionales-sante/reunion/2020-03-18.yaml
  agences-regionales-sante/reunion/2020-03-19.yaml
Labels: anomalies

#158 ARS Haut de France 05/03
  agences-regionales-sante/hauts-de-france/2020-03-05.yaml
Labels: anomalies, question

#159 ARS Hauts de France 06/03
  agences-regionales-sante/hauts-de-france/2020-03-06.yaml
Labels: anomalies

#219 ministere-sante: 21/02 - 26/02
  ministere-sante/2020-02-21.yaml
  ministere-sante/2020-02-23.yaml
  ministere-sante/2020-02-24.yaml
  ministere-sante/2020-02-25.yaml
  ministere-sante/2020-02-26.yaml
Labels: à vérifier

#149 README.md translated to English
  README.en.md
  README.md
Labels: anomalies

#224 ARS Hauts de France 2103 + Saint Martin 17/03 -> 19/03 + Saint Barthelemy 17/03 -!< 19/03
  agences-regionales-sante/hauts-de-france/2020-03-21.yaml
  agences-regionales-sante/saint-barthelemy/2020-03-17.yaml
  agences-regionales-sante/saint-barthelemy/2020-03-18.yaml
  agences-regionales-sante/saint-barthelemy/2020-03-19.yaml
  agences-regionales-sante/saint-martin/2020-03-17.yaml
  agences-regionales-sante/saint-martin/2020-03-18.yaml
  agences-regionales-sante/saint-martin/2020-03-19.yaml
Labels: anomalies

#229 ARS Guadeloupe 2020-03-21
  agences-regionales-sante/guadeloupe/2020-03-21.yaml
Labels: anomalies

#232 ajout ARS St Martin 2020-03-21
  agences-regionales-sante/saint-martin/2020-03-21.yaml
Labels: anomalies

#189 mise à jour divers fichiers ARS et SPF
  README.md
  agences-regionales-sante/polynesie-francaise/2020-03-16.yaml
  agences-regionales-sante/polynesie-francaise/2020-03-17.yaml
  agences-regionales-sante/polynesie-francaise/2020-03-18.yaml
  agences-regionales-sante/polynesie-francaise/2020-03-19.yaml
  agences-regionales-sante/polynesie-francaise/2020-03-20.yaml
  prefectures/988/2020-03-22.yaml
  sante-publique-france/2020-01-24.yaml
  sante-publique-france/2020-01-28.yaml
  sante-publique-france/2020-01-29.yaml
  sante-publique-france/2020-01-30.yaml
  sante-publique-france/2020-02-07.yaml
Labels: question

#220 Ajout des données pour Mayotte du 1er cas (14/03) à ce jour
  agences-regionales-sante/mayotte/2020-03-14.yaml
  agences-regionales-sante/mayotte/2020-03-17.yaml
  agences-regionales-sante/mayotte/2020-03-18.yaml
  agences-regionales-sante/mayotte/2020-03-19.yaml
  agences-regionales-sante/mayotte/2020-03-20.yaml
  agences-regionales-sante/mayotte/2020-03-21.yaml
  agences-regionales-sante/mayotte/2020-03-22.yaml
Labels: anomalies

#233 Mise à jour des données concernant les cas / régions pour la SPF
  sante-publique-france/2020-01-24.yaml
  sante-publique-france/2020-01-25.yaml
  sante-publique-france/2020-01-26.yaml
  sante-publique-france/2020-01-27.yaml
  sante-publique-france/2020-01-31.yaml
  sante-publique-france/2020-02-03.yaml
  sante-publique-france/2020-02-05.yaml
  sante-publique-france/2020-02-06.yaml
  sante-publique-france/2020-02-08.yaml
  sante-publique-france/2020-02-10.yaml
  sante-publique-france/2020-02-11.yaml
  sante-publique-france/2020-02-12.yaml
  sante-publique-france/2020-02-20.yaml
  sante-publique-france/2020-03-03.yaml
Labels: anomalies

#204 Ajout d'informations README /Ministere-sante
  ministere-sante/README.md
Labels: anomalies

#157 Explication de l'utilisation de github
  README.md
  docs/img/explain_github_0.png
  docs/img/explain_github_1_fork.png
  docs/img/explain_github_2_newfile.png
  docs/img/explain_github_3_newfiletext.png
  docs/img/explain_github_4_branch.png
  docs/img/explain_github_4_branch2.png
  docs/img/explain_github_4_commit.png
  docs/img/explain_github_5_updatedforkbranch.png
  docs/img/explain_github_5_updatedforkmaster.png
  docs/img/explain_github_6_startPR.png
  docs/img/explain_github_7_createPR.png
  docs/img/explain_github_8_PRs.png
  docs/utilise-github.md
Labels: anomalies

#271 ARS Reunion 20-21-22-23/03/2020
  agences-regionales-sante/reunion/2020-03-20.yaml
  agences-regionales-sante/reunion/2020-03-21.yaml
  agences-regionales-sante/reunion/2020-03-22.yaml
  agences-regionales-sante/reunion/2020-03-23.yaml
Labels: à vérifier

#371 ADD SPF 25/03
  sante-publique-france/2020-03-25.yaml
Labels: à vérifier

#369 ADD SPF 25/02
  sante-publique-france/2020-02-25.yaml
Labels: à vérifier

#373 ADD ARS Corse du 25/03
  agences-regionales-sante/corse/2020-03-25.yaml
Labels: anomalies

#378 FIX ARS Normandie nombre de décès
  agences-regionales-sante/normandie/2020-03-18.yaml
  agences-regionales-sante/normandie/2020-03-19.yaml
  agences-regionales-sante/normandie/2020-03-20.yaml
  agences-regionales-sante/normandie/2020-03-21.yaml
  agences-regionales-sante/normandie/2020-03-22.yaml
  agences-regionales-sante/normandie/2020-03-23.yaml
  agences-regionales-sante/normandie/2020-03-24.yaml
Labels: anomalies

#379 ADD ARS Reunion 25/03
  agences-regionales-sante/reunion/2020-03-25.yaml
Labels: à vérifier

#372 ADD ARS Centre Val de Loire du 25/03
  agences-regionales-sante/centre-val-de-loire/2020-03-25.yaml
Labels: à vérifier

#380 ADD ARS Nouvelle Aquitaine 25/03 - FIX ARS Nouvelle Aquitaine guéris 24/03
  agences-regionales-sante/nouvelle-aquitaine/2020-03-24.yaml
  agences-regionales-sante/nouvelle-aquitaine/2020-03-25.yaml
Labels: à vérifier

#398 FIX ARS Hauts de France 16/03
  agences-regionales-sante/hauts-de-france/2020-03-16.yaml
Labels: à vérifier

#399 FIX ARS Hauts de France 17/03
  agences-regionales-sante/hauts-de-france/2020-03-17.yaml
Labels: à vérifier

#400 ADD ARS Saint-Barthelemy du 25/03
  agences-regionales-sante/saint-barthelemy/2020-03-25.yaml
Labels: à vérifier

#401 ADD ARS Saint-Martin du 25/03
  agences-regionales-sante/saint-martin/2020-03-25.yaml
Labels: à vérifier

#405 ADD ARS Corse du 26/03
  agences-regionales-sante/corse/2020-03-26.yaml
Labels: à vérifier

#388 ADD Ministère de la Santé 25/03
  ministere-sante/2020-03-25.yaml
Labels: anomalies

#383 ADD ARS pour Bretagne du 25/03
  agences-regionales-sante/bretagne/2020-03-25.yaml
Labels: anomalies

#406 ADD ARS LA Réunion du 26/03
  agences-regionales-sante/reunion/2020-03-26.yaml
Labels: anomalies

#417 ADD ARS PACA du 26/03
  agences-regionales-sante/provence-alpes-cote-dazur/2020-03-26.yaml
Labels: à vérifier

#420 ADD ARS Guyane 26/03
  agences-regionales-sante/guyane/2020-03-26.yaml
Labels: à vérifier

#416 ADD ARS Centre Val de Loire du 26/03
  agences-regionales-sante/centre-val-de-loire/2020-03-26.yaml
Labels: à vérifier

#414 ADD ARS Bourgogne-Franche-Comté 26/03
  agences-regionales-sante/bourgogne-franche-comte/2020-03-26.yaml
Labels: à vérifier

#411 ADD ARS Normandie 26/03
  agences-regionales-sante/normandie/2020-03-26.yaml
Labels: anomalies

#421 ADD ARS Occitanie 26/03
  agences-regionales-sante/occitanie/2020-03-26.yaml
Labels: à vérifier

#413 ADD ARS Pays de la Loire 26/03
  agences-regionales-sante/pays-de-la-loire/2020-03-26.yaml
Labels: à vérifier

#418 ADD ARS Bretagne du 26/03
  agences-regionales-sante/bretagne/2020-03-26.yaml
Labels: à vérifier

#430 ADD SPF 27/03
  sante-publique-france/2020-03-27.yaml
Labels: help wanted, à vérifier

#424 ADD ARS AURA 26/03
  agences-regionales-sante/auvergne-rhone-alpes/2020-03-26.yaml
Labels: à vérifier

#426 ADD ARS Nouvelle-Aquitaine 26/03
  agences-regionales-sante/nouvelle-aquitaine/2020-03-26.yaml
Labels: à vérifier

#428 ADD ARS Martinique 26/03
  agences-regionales-sante/martinique/2020-03-26.yaml
Labels: à vérifier

#431 ADD DSP Polynésie française 26/03
  agences-regionales-sante/polynesie-francaise/2020-03-26.yaml
Labels: à vérifier

#425 ADD ARS Grand-Est 26/03
  agences-regionales-sante/grand-est/2020-03-26.yaml
Labels: à vérifier

#429 ADD ARS Mayotte 27/03
  agences-regionales-sante/mayotte/2020-03-27.yaml
Labels: à vérifier

#432 ADD ARS Normandie 27/03
  agences-regionales-sante/normandie/2020-03-27.yaml
Labels: à vérifier

#446 ADD ARS Centre Val de Loire du 27/03
  agences-regionales-sante/centre-val-de-loire/2020-03-27.yaml
Labels: à vérifier

#447 ADD ARS Guyane du 28/03
  agences-regionales-sante/guyane/2020-03-28.yaml
Labels: à vérifier

#450 ADD ARS Reunion du 28/03
  agences-regionales-sante/reunion/2020-03-28.yaml
Labels: à vérifier

#451 ADD ARS Guadeloupe du 28/03
  agences-regionales-sante/guadeloupe/2020-03-28.yaml
Labels: anomalies

#456 ADD ARS Centre Val de Loire du 29/03
  agences-regionales-sante/centre-val-de-loire/2020-03-29.yaml
Labels: à vérifier

#448 ADD ARS Guyane du 27/03
  agences-regionales-sante/guyane/2020-03-27.yaml
Labels: à vérifier

#455 ADD ARS Guadeloupe du 29/03
  agences-regionales-sante/guadeloupe/2020-03-29.yaml
Labels: à vérifier

#443 ADD ARS Bretagne 27/03
  agences-regionales-sante/bretagne/2020-03-27.yaml
Labels: à vérifier

#444 ADD ARS Centre-Val de Loire 28/03
  agences-regionales-sante/centre-val-de-loire/2020-03-28.yaml
Labels: à vérifier

#453 Ajout chiffres casConfirmes du 26/03
  ministere-sante/2020-03-26.yaml
Labels: à vérifier

#460 ADD ARS HDF 29/03
  agences-regionales-sante/hauts-de-france/2020-03-29.yaml
Labels: à vérifier

#462 ADD ARS Guyane 29/03
  agences-regionales-sante/guyane/2020-03-29.yaml
Labels: à vérifier

#461 ADD ARS HDF 28/03
  agences-regionales-sante/hauts-de-france/2020-03-28.yaml
Labels: à vérifier

#441 ADD ARS Auvergne-Rhône-Alpes 27/03
  agences-regionales-sante/auvergne-rhone-alpes/2020-03-27.yaml
Labels: à vérifier

#463 ADD ARS Martinique 29/03
  agences-regionales-sante/martinique/2020-03-29.yaml
Labels: à vérifier

#452 Ajout du nombre de décès du 28/02/2020 (idem la veille)
  ministere-sante/2020-02-28.yaml
Labels: à vérifier

#437 Bulletin ARS Pays de la Loire du 27-03-2020
  agences-regionales-sante/pays-de-la-loire/2020-03-27.yaml
Labels: à vérifier

#427 ADD Pref-Region Bretagne 27/03
  prefectures-regions/README.md
  prefectures-regions/bretagne/2020-03-27.yaml
Labels: à vérifier

#442 ADD ARS ARS Bretagne 28/03
  agences-regionales-sante/bretagne/2020-03-28.yaml
Labels: à vérifier

#454 ADD ARS Corse du 27/03
  agences-regionales-sante/corse/2020-03-27.yaml
Labels: à vérifier

#449 ADD ARS Reunion du 27/03
  agences-regionales-sante/reunion/2020-03-27.yaml
Labels: à vérifier
